org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.200
loader_version_range=[1,)
blueprint_version=8.0.6
blueprint_version_range=[8.0.0,9.0.0)

mod_id=easel_does_it
mod_name=Easel Does It
mod_license=All Rights Reserved
mod_version=2.0.0
mod_group_id=com.dolthhaven.easeldoesit
mod_authors=DoltHHaven, Glyphy
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
