modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/thelegitdolt/easel-does-it/issues" #optional

[[mods]] #mandatory
    modId="easel_does_it"
    version="2.0.0"
    displayName="Easel Does It"
    authors="${mod_authors}" #optional
    description='''Doltguymack'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
    config="easel_does_it.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"


[[dependencies.easel_does_it]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.easel_does_it]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId = "blueprint"
    type = "required"
    versionRange = "${blueprint_version_range}"
    ordering = "AFTER"
    side = "BOTH"
